/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_de_programacion_de_citas;

/**
 *
 * @author LAPTOP
 */
public class DISEÑOPACIENTES extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DISEÑOPACIENTES.class.getName());

    /**
     * Creates new form DISEÑOPACIENTES
     */
    public DISEÑOPACIENTES() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CÓDIGO:");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("DNI:");

        jLabel4.setText("EDAD:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtDNI.addActionListener(this::txtDNIActionPerformed);

        txtEdad.addActionListener(this::txtEdadActionPerformed);

        jLabel5.setText("TELÉFONO");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel6.setText("REGISTRO DE DATOS");

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOMBRE", "DNI", "EDAD", "TELEFONO", "MEDICAMENTO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("MEDICAMENTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEnviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 577, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnBuscar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnEnviar)
                            .addComponent(btnLimpiar))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String codigo = txtCodigo.getText().trim();
    String nombre = txtNombre.getText().trim();
    String dni = txtDNI.getText().trim();
    String edad = txtEdad.getText().trim();
    String telefono = txtTelefono.getText().trim();
    String medicamento = txtMedicamento.getText().trim();

    // Validación de campos vacíos
    if (codigo.isEmpty() || nombre.isEmpty() || dni.isEmpty() || edad.isEmpty() || telefono.isEmpty() || medicamento.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // CORRECCIÓN: Se cambia jTable3 por jTable1
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // Agregar la nueva fila a la tabla con los datos capturados
    modelo.addRow(new Object[]{codigo, nombre, dni, edad, telefono,medicamento});

    // Limpiar los campos de texto
    txtCodigo.setText("");
    txtNombre.setText("");
    txtDNI.setText("");
    txtEdad.setText("");
    txtTelefono.setText("");
    txtMedicamento.setText("");
    txtCodigo.requestFocus();
    
// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String codigoBuscado = txtCodigo.getText().trim();
if (codigoBuscado.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un código para buscar.");
    return;
}

java.io.File archivo = new java.io.File("pacientes.txt");
if (!archivo.exists()) {
    javax.swing.JOptionPane.showMessageDialog(this, "El archivo 'pacientes.txt' aún no existe.");
    return;
}

boolean encontrado = false;
try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
    String linea;
    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split(";");
        if (datos.length == 6 && datos[0].equalsIgnoreCase(codigoBuscado)) {
            txtNombre.setText(datos[1]);
            txtDNI.setText(datos[2]);
            txtEdad.setText(datos[3]);
            txtTelefono.setText(datos[4]);
            txtMedicamento.setText(datos[6]);

            javax.swing.JOptionPane.showMessageDialog(this, "¡Paciente encontrado!");
            encontrado = true;
            break;
        }
    }
  br.close();
    if (!encontrado) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún paciente con ese código.");
    }
} catch (java.io.IOException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
String codigoModificar = txtCodigo.getText().trim();
if (codigoModificar.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el código del paciente a modificar.");
    return;
}

java.io.File archivoOriginal = new java.io.File("pacientes.txt");
if (!archivoOriginal.exists()) {
    javax.swing.JOptionPane.showMessageDialog(this, "El archivo 'pacientes.txt' no existe.");
    return;
}

java.util.ArrayList<String> lineasGuardar = new java.util.ArrayList<>();
boolean modificado = false;

try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivoOriginal))) {
    String linea;
    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split(";");
        if (datos.length == 6 && datos[0].equalsIgnoreCase(codigoModificar)) {
            String nuevaLinea = codigoModificar + ";" + txtNombre.getText() + ";" + txtDNI.getText() + ";" + txtEdad.getText() + ";" + txtTelefono.getText() + ";" + txtMedicamento.getText();
            lineasGuardar.add(nuevaLinea);
            modificado = true;
        } else {
            lineasGuardar.add(linea);
        }
    }
} catch (java.io.IOException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al leer para modificar: " + e.getMessage());
    return;
}

try (java.io.FileWriter fw = new java.io.FileWriter(archivoOriginal, false)) {
    for (String l : lineasGuardar) {
        fw.write(l + System.lineSeparator());
    }

    if (modificado) {
        javax.swing.JOptionPane.showMessageDialog(this, "Paciente modificado con éxito.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Código no encontrado.");
    }
} catch (java.io.IOException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar cambios: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
String codigoEliminar = txtCodigo.getText().trim();
if (codigoEliminar.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el código del paciente a eliminar.");
    return;
}

java.io.File archivoOriginal = new java.io.File("pacientes.txt");
if (!archivoOriginal.exists()) return;

java.util.ArrayList<String> lineasGuardar = new java.util.ArrayList<>();
boolean eliminado = false;

try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivoOriginal))) {
    String linea;
    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split(";");
        if (datos.length == 6 && datos[0].equalsIgnoreCase(codigoEliminar)) {
            eliminado = true;
        } else {
            lineasGuardar.add(linea);
        }
    }
} catch (java.io.IOException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al leer para eliminar: " + e.getMessage());
    return;
}

try (java.io.FileWriter fw = new java.io.FileWriter(archivoOriginal, false)) {
    for (String l : lineasGuardar) {
        fw.write(l + System.lineSeparator());
    }

    if (eliminado) {
        javax.swing.JOptionPane.showMessageDialog(this, "Paciente eliminado del archivo.");
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDNI.setText("");
        txtEdad.setText("");
        txtTelefono.setText("");
        txtMedicamento.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Código no encontrado.");
    }
} catch (java.io.IOException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();

if (modelo.getRowCount() == 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "No hay datos en la tabla para enviar.");
    return;
}

try (java.io.FileWriter archivo = new java.io.FileWriter("pacientes.txt", true)) {
    for (int fila = 0; fila < modelo.getRowCount(); fila++) {
        String codigo = modelo.getValueAt(fila, 0).toString();
        String nombre = modelo.getValueAt(fila, 1).toString();
        String dni = modelo.getValueAt(fila, 2).toString();
        String edad = modelo.getValueAt(fila, 3).toString();
        String telefono = modelo.getValueAt(fila, 4).toString();
        String medicamento = modelo.getValueAt(fila,5).toString();

        archivo.write(codigo + ";" + nombre + ";" + dni + ";" + edad + ";" + telefono + ";" + medicamento);
        archivo.write(System.lineSeparator());
    }
    archivo.close();
    javax.swing.JOptionPane.showMessageDialog(this, "Contenido guardado en 'pacientes.txt' correctamente.");
    modelo.setRowCount(0);

} catch (java.io.IOException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en el archivo: " + e.getMessage());
}     
// TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
txtCodigo.setText("");
txtNombre.setText("");
txtDNI.setText("");
txtEdad.setText("");
txtTelefono.setText("");
txtMedicamento.setText("");
txtCodigo.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
