/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_de_programacion_de_citas;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormularioMedicamentos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioMedicamentos.class.getName());

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {},
            new String[] {"Código", "Nombre", "Componente", "Laboratorio", "Stock"}
        );
        jTable3.setModel(modelo);
    }

    public FormularioMedicamentos() {
        initComponents();
        configurarTabla(); 
        setLocationRelativeTo(null); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtComponente = new javax.swing.JTextField();
        txtLaboratorio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Componente Activo:");

        jLabel4.setText("Laboratorio:");

        jLabel5.setText("Stock:");

        txtComponente.addActionListener(this::txtComponenteActionPerformed);

        txtStock.addActionListener(this::txtStockActionPerformed);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Componente", "Laboratorio", "Stock"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Buscar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Modificar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Eliminar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Enviar");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jLabel6.setText("FORMULARIO DE MEDICAMENTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtComponente)
                                    .addComponent(txtLaboratorio)
                                    .addComponent(txtStock))
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton5)
                        .addComponent(jButton4)))
                .addContainerGap(338, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String codigo = txtCodigo.getText();
String nombre = txtNombre.getText();
String componente = txtComponente.getText();
String laboratorio = txtLaboratorio.getText();
String stock = txtStock.getText();

if (codigo.isEmpty() || nombre.isEmpty() || componente.isEmpty() || laboratorio.isEmpty() || stock.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
    return;
}

DefaultTableModel modelo = (DefaultTableModel) jTable3.getModel();

modelo.addRow(new Object[]{
    codigo,
    nombre,
    componente,
    laboratorio,
    stock
});

txtCodigo.setText("");
txtNombre.setText("");
txtComponente.setText("");
txtLaboratorio.setText("");
txtStock.setText("");
txtCodigo.requestFocus();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComponenteActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) jTable3.getModel();
    try {
        // Abre o crea el archivo de texto en modo adicion (true)
        FileWriter archivo = new FileWriter("medicamentos.txt", true);
        
        // Recorrer todas las filas de la tabla
        for (int fila = 0; fila < modelo.getRowCount(); fila++) {
            String codigo = modelo.getValueAt(fila, 0).toString();
            String nombre = modelo.getValueAt(fila, 1).toString();
            String componente = modelo.getValueAt(fila, 2).toString();
            String laboratorio = modelo.getValueAt(fila, 3).toString();
            String stock = modelo.getValueAt(fila, 4).toString();
            
            // Escribir en el bloc de notas separado por punto y coma (;)
            archivo.write(codigo + ";" + nombre + ";" + componente + ";" + laboratorio + ";" + stock);
            archivo.write(System.lineSeparator()); // Salto de línea
        }
        archivo.close();
        
        JOptionPane.showMessageDialog(this, "Contenido de la tabla guardado en el archivo correctamente.");
        modelo.setRowCount(0); // Limpia la tabla visual
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String codigoBuscado = txtCodigo.getText().trim();
if (codigoBuscado.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese un código para buscar.");
    return;
}
File archivo = new File("medicamentos.txt");
if (!archivo.exists()) {
    JOptionPane.showMessageDialog(this, "El archivo de registros aún no existe.");
    return;
}
boolean encontrado = false;
try {
    BufferedReader br = new BufferedReader(new FileReader(archivo));
    String linea;
    
    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split(";");

        if (datos.length == 5 && datos[0].equalsIgnoreCase(codigoBuscado)) {
            txtNombre.setText(datos[1]);
            txtComponente.setText(datos[2]);
            txtLaboratorio.setText(datos[3]);
            txtStock.setText(datos[4]);
            
            JOptionPane.showMessageDialog(this, "¡Medicamento encontrado en el archivo!");
            encontrado = true;
            break;
        }
    }
    br.close();

    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "No se encontró ningún medicamento con ese código.");
    }
} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    String codigoEliminar = txtCodigo.getText().trim();
    if (codigoEliminar.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el código a eliminar.");
        return;
    }

    File archivoOriginal = new File("medicamentos.txt");
    if (!archivoOriginal.exists()) return;

    ArrayList<String> lineasGuardar = new ArrayList<>();
    boolean eliminado = false;

    try {
        BufferedReader br = new BufferedReader(new FileReader(archivoOriginal));
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");
            if (datos.length == 5 && datos[0].equalsIgnoreCase(codigoEliminar)) {
                eliminado = true; 
            } else {
                lineasGuardar.add(linea);
            }
        }
        br.close();

        FileWriter fw = new FileWriter(archivoOriginal, false); 
        for (String l : lineasGuardar) {
            fw.write(l);
            fw.write(System.lineSeparator());
        }
        fw.close();

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Medicamento eliminado del archivo.");
            txtCodigo.setText(""); txtNombre.setText(""); txtComponente.setText(""); txtLaboratorio.setText(""); txtStock.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Código no encontrado.");
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error en la operación: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String codigoModificar = txtCodigo.getText().trim();
    if (codigoModificar.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el código a modificar.");
        return;
    }

    File archivoOriginal = new File("medicamentos.txt");
    if (!archivoOriginal.exists()) return;

    ArrayList<String> lineasGuardar = new ArrayList<>();
    boolean modificado = false;

    try {
        BufferedReader br = new BufferedReader(new FileReader(archivoOriginal));
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");
            if (datos.length == 5 && datos[0].equalsIgnoreCase(codigoModificar)) {
                // Junta los nuevos datos de las casillas en una nueva línea
                String nuevaLinea = codigoModificar + ";" + txtNombre.getText() + ";" + txtComponente.getText() + ";" + txtLaboratorio.getText() + ";" + txtStock.getText();
                lineasGuardar.add(nuevaLinea);
                modificado = true;
            } else {
                lineasGuardar.add(linea);
            }
        }
        br.close();

        FileWriter fw = new FileWriter(archivoOriginal, false);
        for (String l : lineasGuardar) {
            fw.write(l);
            fw.write(System.lineSeparator());
        }
        fw.close();

        if (modificado) {
            JOptionPane.showMessageDialog(this, "Medicamento modificado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Código no encontrado.");
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioMedicamentos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComponente;
    private javax.swing.JTextField txtLaboratorio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
